development:
  AWS_ACCESS_KEY_ID: AKIAIZWJA6T4AWZFHHWQ
  AWS_SECRET_KEY_ID: yHzWpwBEPGfnCdJQVVl1ydSKCMKxU6tJCVH0BFje
  S3_BUCKET_NAME: setbuck
  AWS_REGION: ap-south-1

production:
  AWS_ACCESS_KEY_ID: AKIAIZWJA6T4AWZFHHWQ
  AWS_SECRET_KEY_ID: yHzWpwBEPGfnCdJQVVl1ydSKCMKxU6tJCVH0BFje
  S3_BUCKET_NAME: setbuck
  AWS_REGION: ap-south-1